version: "3.9"
services:
  service-video:
   build: ../microservicio-video
   ports:
     - 8080:3007
  service-crud:
   build: ../online-store
   ports:
     - 8081:3008
  service-registration:
   build: ../
   ports:
     - 8082:3009